### ISSUE TITLE
Install OpenSCAP, SSG,  (and GovReady) on AWS Default Linux

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready#45]
OpenSCAP and SSG does not seem to install on AWS Linux because AWS pins their Linux to their own set of repos. The choice to fix is to either build from source, understand how to adjust which repos are used, or to write AWS to have them include it.

This issue traces details of getting OpenSCAP and SSG to work on AWS. 

See the https://github.com/GovReady/govready/blob/master/Quickstart-Amazon-Linux.md for directions on installing on Amazon Linux.

**Comment by gregelin** [comment]
Switched Amazon quick start guide to use CentOS 6 RPM to install SCAP-Security-Guide. commit 81bfbd0d6fed748f4043a155e513e474e017ef26

**Comment by bkruger99** [comment]
Not sure if this is still being worked on, but here's a spec file that'll compile open-scap on aws linux.  It doesn't include any policies to apply however, that'll still need to be worked out.


[openscap.spec.txt](https://github.com/GovReady/govready/files/781333/openscap.spec.txt)
