### ISSUE TITLE
Error: Cannot retrieve repository metadata (repomd.xml) for repository: epel. Please verify its path and try again

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready#64]
EPEL fails to work to install ecap-security-guide.

error:
```
Error: Cannot retrieve repository metadata (repomd.xml) for repository: epel. Please verify its path and try again
```

Found: http://unix.stackexchange.com/questions/148144/unable-to-pull-epel-repository-metadata

Best fix appears to be:

> The problem is with nss old versions. It cannot talk with Fedora site via curl and use old nss library.
> Just update your nss version to the latest, it solves the problem with the EPEL repo update:

```
$ sudo yum clean all 
$ sudo yum --disablerepo="epel" update nss
```

**Comment by gregelin** [comment]
Confirmed that updating `nss` does fix the issue with EPEL on RHEL 6.4.

**Comment by FantomX1** [comment]
thank you so much

**Comment by mesmaeily** [comment]
your IP is filtred
use VPN connection
